name: Mirror CI

on:
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: mirror-repository
      uses: spyoungtech/mirror-action@v0.5.1
      with:
        REMOTE: git@codeberg.org:aerphanas/minigrep.git
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_KEY }}
        GIT_SSH_NO_VERIFY_HOST: "true"
        DEBUG: "true"
