name: 'mirror codeberg'
on:
  push:
    branches:
        - __mirror
  schedule:
    - cron: '* 3 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: n14s/github-mirror-action@v1.1
        with:
          origin: 'https://codeberg.org/aerphanas/minigrep.git'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
